### ISSUE TITLE
Compile errors in Windows

### ISSUE THREAD

**Issue by novacrazy** [gnzlbg/mimallocator#1]
Fails to compile with a few fatal errors on Windows using `rustc 1.37.0-nightly (929b48ec9 2019-06-21)`, `nightly-x86_64-pc-windows-msvc`

<details>

```
error: failed to run custom build command for `mimalloc-sys v0.1.1`

Caused by:
  process didn't exit successfully: `F:\code\projects\testing\target\debug\build\mimalloc-sys-78444b9d7ac51358\build-script-build` (exit code: 101)
--- stdout
TARGET=x86_64-pc-windows-msvc
HOST=x86_64-pc-windows-msvc
PROFILE=debug
NUM_JOBS=32
OUT_DIR="F:\\code\\projects\\testing\\target\\debug\\build\\mimalloc-sys-5278bb05787e53d0\\out"
BUILD_DIR="F:\\code\\projects\\testing\\target\\debug\\build\\mimalloc-sys-5278bb05787e53d0\\out\\build"
SRC_DIR="C:\\Users\\novacrazy\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\mimalloc-sys-0.1.1"
mimalloc_src_dir="C:\\Users\\novacrazy\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\mimalloc-sys-0.1.1\\mimalloc"
mimalloc_out_src_dir="F:\\code\\projects\\testing\\target\\debug\\build\\mimalloc-sys-5278bb05787e53d0\\out\\build\\mimalloc"
running: "cmake" "F:\\code\\projects\\testing\\target\\debug\\build\\mimalloc-sys-5278bb05787e53d0\\out\\build\\mimalloc" "-G" "Visual Studio 16 2019" "-Thost=x64" "-Ax64" "-DOVERRIDE=OFF"
"-DCMAKE_INSTALL_PREFIX=F:\\code\\projects\\testing\\target\\debug\\build\\mimalloc-sys-5278bb05787e53d0\\out" "-DCMAKE_C_FLAGS= /nologo /MD" "-DCMAKE_C_FLAGS_DEBUG= /nologo /MD" "-DCMAKE_CXX_FLAGS= /nologo /MD" "-DCMAKE_CXX_FLAGS_DEBUG= /nologo /MD" "-DCMAKE_BUILD_TYPE=Debug"
-- The C compiler identification is MSVC 19.20.27508.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type specified as *** Debug ***
-- Output library name   : mimalloc-debug
-- Installation directory: lib/mimalloc-1.0
-- Configuring done
-- Generating done
-- Build files have been written to: F:/code/projects/testing/target/debug/build/mimalloc-sys-5278bb05787e53d0/out/build
running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--"
Microsoft (R) Build Engine version 16.0.461+g6ff56ef63c for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule F:/code/projects/testing/target/debug/build/mimalloc-sys-5278bb05787e53d0/out/build/mimalloc/CMakeLists.txt
  stats.c
  os.c
  segment.c
  page.c
  alloc.c
  alloc-aligned.c
  heap.c
  options.c
  init.c
  Generating Code...
     Creating library F:/code/projects/testing/target/debug/build/mimalloc-sys-5278bb05787e53d0/out/build/Debug/mimalloc-debug.lib and object F:/code/projects/testing/target/debug/build/mimalloc-sys-5278bb05787e53d0/out/build/Debug/mimalloc-debug.exp
alloc.obj : error LNK2019: unresolved external symbol _mi_bin referenced in function _mi_page_malloc [F:\code\projects\testing\target\debug\build\mimalloc-sys-5278bb05787e53d0\out\build\mimalloc.vcxproj]
heap.obj : error LNK2001: unresolved external symbol _mi_bin [F:\code\projects\testing\target\debug\build\mimalloc-sys-5278bb05787e53d0\out\build\mimalloc.vcxproj]
F:\code\projects\testing\target\debug\build\mimalloc-sys-5278bb05787e53d0\out\build\Debug\mimalloc-debug.dll : fatal error LNK1120: 1 unresolved externals [F:\code\projects\testing\target\debug\build\mimalloc-sys-5278bb05787e53d0\out\build\mimalloc.vcxproj]
  Building Custom Rule F:/code/projects/testing/target/debug/build/mimalloc-sys-5278bb05787e53d0/out/build/mimalloc/CMakeLists.txt
  static.c
F:\code\projects\testing\target\debug\build\mimalloc-sys-5278bb05787e53d0\out\build\mimalloc\src\alloc-override.c(13): fatal error C1189: #error:  "It is only possible to override malloc on
Windows when building as a DLL (and linking the C runtime as a DLL)" [F:\code\projects\testing\target\debug\build\mimalloc-sys-5278bb05787e53d0\out\build\mimalloc-obj.vcxproj]
  Building Custom Rule F:/code/projects/testing/target/debug/build/mimalloc-sys-5278bb05787e53d0/out/build/mimalloc/CMakeLists.txt
  stats.c
  os.c
  segment.c
  page.c
  alloc.c
  alloc-aligned.c
  heap.c
  options.c
  init.c
  Generating Code...
  mimalloc-static.vcxproj -> F:\code\projects\testing\target\debug\build\mimalloc-sys-5278bb05787e53d0\out\build\Debug\mimalloc-debug.lib

--- stderr
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_CXX_FLAGS
    CMAKE_CXX_FLAGS_DEBUG


thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\novacrazy\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.40\src\lib.rs:832:5
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.29\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647\/src\libstd\sys_common\backtrace.rs:47
   2: std::sys_common::backtrace::print
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647\/src\libstd\sys_common\backtrace.rs:36
   3: std::panicking::default_hook::{{closure}}
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647\/src\libstd\panicking.rs:198
   4: std::panicking::default_hook
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647\/src\libstd\panicking.rs:212
   5: std::panicking::rust_panic_with_hook
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647\/src\libstd\panicking.rs:475
   6: std::panicking::continue_panic_fmt
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647\/src\libstd\panicking.rs:382
   7: std::panicking::begin_panic_fmt
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647\/src\libstd\panicking.rs:337
   8: cmake::fail
             at C:\Users\novacrazy\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.40\src\lib.rs:832
   9: cmake::run
             at C:\Users\novacrazy\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.40\src\lib.rs:810
  10: cmake::Config::build
             at C:\Users\novacrazy\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.40\src\lib.rs:719
  11: build_script_build::main
             at .\build.rs:52
  12: std::rt::lang_start::{{closure}}<()>
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647\src\libstd\rt.rs:64
  13: std::rt::lang_start_internal::{{closure}}
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647\/src\libstd\rt.rs:49
  14: std::panicking::try::do_call<closure,i32>
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647\/src\libstd\panicking.rs:294
  15: panic_unwind::__rust_maybe_catch_panic
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647\/src\libpanic_unwind\lib.rs:82
  16: std::panicking::try
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647\/src\libstd\panicking.rs:273
  17: std::panic::catch_unwind
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647\/src\libstd\panic.rs:388
  18: std::rt::lang_start_internal
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647\/src\libstd\rt.rs:48
  19: std::rt::lang_start<()>
             at /rustc/929b48ec98aaff2239257574b5897f419cec2647\src\libstd\rt.rs:64
  20: main
  21: invoke_main
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  22: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  23: BaseThreadInitThunk
  24: RtlUserThreadStart

warning: build failed, waiting for other jobs to finish...
error: build failed
```

</details>

**Comment by aleksmelnikov** [comment]
May be this path will fix the error: https://github.com/microsoft/mimalloc/pull/22
So you can try to build `mimalloc-sys` with custom repo for `mimalloc`: https://github.com/myd7349/mimalloc/tree/win32-cmake-patch

**Comment by novacrazy** [comment]
Hmm, that fixes the override issues, but still gives me a:

`error LNK2019: unresolved external symbol _mi_bin referenced in function _mi_page_malloc`

**Comment by gnzlbg** [comment]
@novacrazy at this point you are probably going to have to mostly fix it yourself (with our help) and send a PR. 

The first thing you can try is make sure that `mimalloc` itself builds properly in your system (e.g. clone the microsoft/mimalloc repo), configure it, build it, run its tests, etc.

Once you are that far, then clone this repo and try to build mimalloc-sys. If it fails, run the build in `-vv` (very verbose mode), and figure out which differences in configuring, building, etc. are there between what mimalloc-sys does and what you manually did for mimalloc, and then try to get it to do the same. 

After that, you might still run into issues linking the library to your rust projects, but once you are there, we can help with that.

---

Right now, inspecting your error message, it appears that configuring fails because cmake spits warnings. I am not sure if that also happens when configuring mimalloc manually, or whether that's something that the `cmake` crate does by default. We might need to allow warnings on windows via the `cmake` crate (either by passing it an option, or by sending a PR there upstream).

**Comment by novacrazy** [comment]
It seems that the default target, `install`, attempts to build both the shared and static versions of the library, and it's the shared version that causes issues. However, attempting to build only `mimalloc-static` doesn't "install" the files in the correct location... 

Funny enough, I was able to get mimallocator working accidentally by having it partially build the `install` target and failing, then switching to `mimalloc-static` and compiling, and everything ran fine because the two attempts layered together a correct output.

If there is a way to avoid the shared library in cmake while installing the other files, I'm not aware of it. I have little experience with cmake.
